### ISSUE TITLE
Initial Traceback From First Use, Setup.py quirk?

### ISSUE THREAD

**Issue by mattreid** [abourget/inkscapeslide#14]
It's possible I messed up the install somehow, but after running the setup.py script and trying to run 'inkscapeslide' on an SVG configured for inkscapelide already, I got this:

```
Traceback (most recent call last):
File "/usr/bin/inkscapeslide", line 9, in <module>
load_entry_point('InkscapeSlide==1.0', 'console_scripts', 'inkscapeslide')()
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 337, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2307, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2017, in load
entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named inkscapeslide
```

I ran the setup.py file again, and then tried to use inkscapeslide again and this time it worked fine. Seems like there was an issue the first time the install script ran that ended up working the second time. It had installed enough to provide an autocomplete for inkscapeslide though.

Output from the first run of setup.py (this was on Fedora 17 64bit):
$ sudo python inkscapeslide/setup.py install 
running install
running bdist_egg
running egg_info
creating InkscapeSlide.egg-info
writing requirements to InkscapeSlide.egg-info/requires.txt
writing InkscapeSlide.egg-info/PKG-INFO
writing top-level names to InkscapeSlide.egg-info/top_level.txt
writing dependency_links to InkscapeSlide.egg-info/dependency_links.txt
writing entry points to InkscapeSlide.egg-info/entry_points.txt
writing manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
writing manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/InkscapeSlide-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing InkscapeSlide-1.0-py2.7.egg
creating /usr/lib/python2.7/site-packages/InkscapeSlide-1.0-py2.7.egg
Extracting InkscapeSlide-1.0-py2.7.egg to /usr/lib/python2.7/site-packages
Adding InkscapeSlide 1.0 to easy-install.pth file
Installing inkscapeslide script to /usr/bin

Installed /usr/lib/python2.7/site-packages/InkscapeSlide-1.0-py2.7.egg
Processing dependencies for InkscapeSlide==1.0
Searching for pyPdf
Reading http://pypi.python.org/simple/pyPdf/
Reading http://pybrary.net/pyPdf/
Reading http://stompstompstomp.com/pyPdf/
Download error on http://stompstompstomp.com/pyPdf/: [Errno -2] Name or service not known -- Some packages may not be found!
Reading http://stompstompstomp.com/pyPdf/
Download error on http://stompstompstomp.com/pyPdf/: [Errno -2] Name or service not known -- Some packages may not be found!
Reading http://stompstompstomp.com/pyPdf/
Download error on http://stompstompstomp.com/pyPdf/: [Errno -2] Name or service not known -- Some packages may not be found!
Reading http://stompstompstomp.com/pyPdf/
Download error on http://stompstompstomp.com/pyPdf/: [Errno -2] Name or service not known -- Some packages may not be found!
Best match: pyPdf 1.13
Downloading http://pybrary.net/pyPdf/pyPdf-1.13.zip
Processing pyPdf-1.13.zip
Writing /tmp/easy_install-xBRTBi/pyPdf-1.13/setup.cfg
Running pyPdf-1.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xBRTBi/pyPdf-1.13/egg-dist-tmp-kARFwc
zip_safe flag not set; analyzing archive contents...
Adding pyPdf 1.13 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/pyPdf-1.13-py2.7.egg
Searching for lxml==2.3.5
Best match: lxml 2.3.5
Adding lxml 2.3.5 to easy-install.pth file

Using /usr/lib64/python2.7/site-packages
Finished processing dependencies for InkscapeSlide==1.0

Second, more successful run (this time from the directory itself):
$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating InkscapeSlide.egg-info
writing requirements to InkscapeSlide.egg-info/requires.txt
writing InkscapeSlide.egg-info/PKG-INFO
writing top-level names to InkscapeSlide.egg-info/top_level.txt
writing dependency_links to InkscapeSlide.egg-info/dependency_links.txt
writing entry points to InkscapeSlide.egg-info/entry_points.txt
writing manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
reading manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
writing manifest file 'InkscapeSlide.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/inkscapeslide
copying inkscapeslide/**init**.py -> build/lib/inkscapeslide
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/inkscapeslide
copying build/lib/inkscapeslide/**init**.py -> build/bdist.linux-x86_64/egg/inkscapeslide
byte-compiling build/bdist.linux-x86_64/egg/inkscapeslide/**init**.py to **init**.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying InkscapeSlide.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/InkscapeSlide-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing InkscapeSlide-1.0-py2.7.egg
removing '/usr/lib/python2.7/site-packages/InkscapeSlide-1.0-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/InkscapeSlide-1.0-py2.7.egg
Extracting InkscapeSlide-1.0-py2.7.egg to /usr/lib/python2.7/site-packages
InkscapeSlide 1.0 is already the active version in easy-install.pth
Installing inkscapeslide script to /usr/bin

Installed /usr/lib/python2.7/site-packages/InkscapeSlide-1.0-py2.7.egg
Processing dependencies for InkscapeSlide==1.0
Searching for lxml==2.3.5
Best match: lxml 2.3.5
Adding lxml 2.3.5 to easy-install.pth file

Using /usr/lib64/python2.7/site-packages
Searching for pyPdf==1.13
Best match: pyPdf 1.13
Processing pyPdf-1.13-py2.7.egg
pyPdf 1.13 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/pyPdf-1.13-py2.7.egg
Finished processing dependencies for InkscapeSlide==1.0

**Comment by abourget** [comment]
From what I can see, it seems the host that hosts pyPdf was offline on your
first run and available on the second.

Otherwise I see no obvious problem

Alexandre
